name: Healthcare App CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Stop Existing Containers
      run: |
        sudo docker stop $(sudo docker ps -aq) || true
        sudo docker rm $(sudo docker ps -aq) || true

    - name: Build Docker Image
      run: |
        cd ~/healthcare-deployment
        sudo docker build -t healthcare-app .

    - name: Run Docker Container
      run: |
        sudo docker run -d -p 5000:5000 healthcare-app
